# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79bc3b2e46220c0b08d2fccbbad1125e65e40edad93a160c15abede15c4a97ff64dd556a999b29daca7e2bb1c2cbae1b1e8cfeea75d18f5ff78a5551da85377f

test:
  secret_key_base: 26474d19fcabded16af0097a9832669600be0868ae448d40b4b8e64b0c4847c63df742273d246f261cb3da43a2713cf19c79e969c4b980e8f1eca9315cef1633

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
